using System.Xml.Serialization;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace EnvCrypt.Core.EncrypedData.Xml
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot(Namespace = "", IsNullable = false)]
    public class EnvCryptEncryptedData
    {

        private EnvCryptEncryptedDataCategory[] itemsField;

        /// <remarks/>
        [XmlElement("Category", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EnvCryptEncryptedDataCategory[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class EnvCryptEncryptedDataCategory
    {

        private EnvCryptEncryptedDataCategoryEntry[] entryField;

        private string nameField;

        /// <remarks/>
        [XmlElement("Entry", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EnvCryptEncryptedDataCategoryEntry[] Entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class EnvCryptEncryptedDataCategoryEntry
    {

        private EnvCryptEncryptedDataCategoryEntryDecryption[] decryptionField;

        private EnvCryptEncryptedDataCategoryEntryEncryptedValue[] encryptedValueField;

        private string nameField;

        /// <remarks/>
        [XmlElement("Decryption", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EnvCryptEncryptedDataCategoryEntryDecryption[] Decryption
        {
            get
            {
                return this.decryptionField;
            }
            set
            {
                this.decryptionField = value;
            }
        }

        /// <remarks/>
        [XmlElement("EncryptedValue", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public EnvCryptEncryptedDataCategoryEntryEncryptedValue[] EncryptedValue
        {
            get
            {
                return this.encryptedValueField;
            }
            set
            {
                this.encryptedValueField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class EnvCryptEncryptedDataCategoryEntryDecryption
    {

        private string keyNameField;

        private string hashField;

        private string algoField;

        /// <remarks/>
        [XmlAttribute()]
        public string KeyName
        {
            get
            {
                return this.keyNameField;
            }
            set
            {
                this.keyNameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Hash
        {
            get
            {
                return this.hashField;
            }
            set
            {
                this.hashField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string Algo
        {
            get
            {
                return this.algoField;
            }
            set
            {
                this.algoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true)]
    public partial class EnvCryptEncryptedDataCategoryEntryEncryptedValue
    {

        private string valueField;

        /// <remarks/>
        [XmlText()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}
